### ISSUE TITLE
Macro to disable Logs

### ISSUE THREAD

**Issue by darshanmirajkar** [tobozo/ESP32-targz#13]
Hello,

Please Add the Macro to disable tar_error_logger and tar_debug_logger. Since i am using this library from Platform IO i can use it in .ini file

**Comment by tobozo** [comment]
Hello,

There's no 'macro' for that but two functions you can use to make the decompression more silent on Serial:

    setProgressCallback( targzNullProgressCallback );

    setLoggerCallback( targzNullLoggerCallback );

**Comment by darshanmirajkar** [comment]
Thank you... I'll chek this and let you know

**Comment by darshanmirajkar** [comment]
I am trying to use same in main.cpp give error no storage class or type specifier

**Comment by darshanmirajkar** [comment]
Thank you... It is working
