### ISSUE TITLE
'tarGzFs' was not declared in this scope

### ISSUE THREAD

**Issue by frankcohen** [tobozo/ESP32-targz#28]
I am using Arduino IDE 1.8.13 on MacOS 11.2.1. I have this in a sketch:

// ESP32-targz
#define DEST_FS_USES_SD
#include <ESP32-targz.h>

boolean tarDecompress()
{
      tarGzFs.begin();
      . . .
}

/Users/frankcohen/Documents/Arduino/ShowRunner/ShowRunner.ino: In function 'boolean tarDecompress()':
ShowRunner:512:7: error: 'tarGzFs' was not declared in this scope
       tarGzFs.begin();
       ^

Bet I'm doing something dumb. Ideas?

**Comment by frankcohen** [comment]
tarGzFs is defined as SD in the .h file. I already do SD.begin() in the setup() method. I commented out tarGzFs.begin() and it complies.

**Comment by tobozo** [comment]
Hey Frank thanks for reporting this.

Looks like there's some inconsistency in the documentation, the filesystem object should be inherited as `tarGzFS` instead of `tarGzFs`.

I'll update the ReadMe accordingly, thanks for spotting that !

**Comment by frankcohen** [comment]
Glad to help. Thank you for your effort.

**Comment by tobozo** [comment]
documentation is fixed in the latest release (currently propagating), closing this issue as solved, thanks again for your feedback :+1
