### ISSUE TITLE
Empty file inside .tar archive returns error -34

### ISSUE THREAD

**Issue by JamPaul97** [tobozo/ESP32-targz#48]
If there is an empty file inside a .tar file when trying to extract it the process exit with code -34. A log file can be provided if needed.

**Comment by tobozo** [comment]
hey @JamPaul97 thanks for reporting that.

I'll try to reproduce the issue and post my folluwup here.

**Comment by tobozo** [comment]
update: thanks to your feedback I could reproduce and [fix the issue](https://github.com/tobozo/ESP32-targz/commit/d2d25b5b9f512773dda5ce0ad2f4b32f04c7ce20).

I'll produce a new release soon.

**Comment by tobozo** [comment]
[New release available](https://github.com/tobozo/ESP32-targz/releases/tag/v1.1.2), it will propagate soon to arduino and platformio library registries.

Closing this as solved, thanks again for your feedback :+1:
