### ISSUE TITLE
Readme document outdated

### ISSUE THREAD

**Issue by ryanhz** [tobozo/ESP32-targz#56]
In the readme document:

`if( ! GZUnpacker->gzUpdater(tarGzFS, firmwareFile, /*don't restart after update*/false ) ) {
     Serial.printf("gzUpdater failed with return code #%d\n", GZUnpacker->tarGzGetError() );
}`

Should be changed to

`if( ! GZUnpacker->gzUpdater(tarGzFS, firmwareFile, U_FLASH, /*don't restart after update*/false ) ) {
     Serial.printf("gzUpdater failed with return code #%d\n", GZUnpacker->tarGzGetError() );
}`

**Comment by tobozo** [comment]
hey thanks for pointing that out :+1: 

I'm not sure ESP8266 and ESP32 use the same macros for flash/spiffs partitions though, will test that later and edit accordingly.

**Comment by ryanhz** [comment]
Thanks for your prompt reply.
Actually it is not a micro, it is a function in GzUnpacker class:
`bool    gzUpdater( fs::FS &sourceFS, const char* gz_filename, int partition = U_FLASH, bool restart_on_update = true ); `

**Comment by ryanhz** [comment]
Thank you for your update and this amazing library. Closing this issue now.
