### ISSUE TITLE
Overwrite the file

### ISSUE THREAD

**Issue by workpage2** [tobozo/ESP32-targz#7]
Do I have to delete the old versions of the files before unpacking, or will they be safely overwritten?

**Comment by tobozo** [comment]
this library was written with the assumption that the behaviour of `fs::FS` when opening an existing file with the `FILE_WRITE` flag is to truncate that file

please let me know if you observe a different result

**Comment by tobozo** [comment]
closing this as inactive, feel free to reopen if you find ou it's not safely overwritten
